on:
  push:
    # branches: main
name: Build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'
          cache-dependency-path: ./yarn.lock
      - run: yarn install --immutable
      - name: Build
        run: yarn build
      - name: Upload built artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/
