on:
  push:
    # branches: main
name: Development Release
jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'
          cache-dependency-path: ./yarn.lock
      - run: yarn install --immutable
      - name: Build
        run: yarn build
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: dist
          prerelease: true
