on:
  push:
    branches-ignore:
      - main # Because "Require branches to be up to date before merging" is enabled for main. The checking will be completed before pull request can be merged.
name: Continuous Integration
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'
          cache-dependency-path: ./yarn.lock
      - run: yarn install --immutable
      - name: Linting
        run: yarn lint
      - name: Formatting
        run: yarn format-check
      - name: Type Checking
        run: yarn type-check
      - name: Unit Testing
        run: yarn test:unit
      - name: Build
        run: yarn build-only
      - name: End-to-End Testing
        run: yarn test:e2e
